// User profile type definitions for FoodBuddy

export interface UserProfile {
  // Required fields
  userId: string; // UUID generated by database
  username: string; // Display name
  email: string; // Login account
  avatarUrl?: string; // Cloudinary uploaded image URL
  createdAt: Date;
  updatedAt: Date;

  // Food preferences and interests
  cravings: string[]; // Current food cravings (e.g., ramen, bubble tea)
  favoriteCuisines: string[]; // Preferred cuisines (Chinese, Thai, Japanese, etc.)
  favoriteRestaurants: string[]; // List of bookmarked restaurant IDs
  dietaryRestrictions: string[]; // Dietary restrictions (vegan, halal, dairy-free)
  allergies: string[]; // Allergy information (peanut, shellfish, etc.)
}

// Partial profile for updates
export type UserProfileUpdate = Partial<Omit<UserProfile, 'userId' | 'createdAt'>>;

// Common options for user selection
export const COMMON_CRAVINGS = [
  'Ramen',
  'Bubble Tea',
  'Pizza',
  'Sushi',
  'Burgers',
  'Tacos',
  'Pasta',
  'Fried Chicken',
  'BBQ',
  'Salad',
  'Sandwich',
  'Noodles',
  'Curry',
  'Dumplings',
  'Seafood',
] as const;

export const COMMON_CUISINES = [
  'Chinese',
  'Japanese',
  'Korean',
  'Thai',
  'Vietnamese',
  'Italian',
  'Mexican',
  'American',
  'French',
  'Indian',
  'Mediterranean',
  'Middle Eastern',
  'Spanish',
  'Greek',
  'Brazilian',
] as const;

export const COMMON_DIETARY_RESTRICTIONS = [
  'Vegetarian',
  'Vegan',
  'Halal',
  'Kosher',
  'Gluten-Free',
  'Dairy-Free',
  'Nut-Free',
  'Low-Carb',
  'Keto',
  'Paleo',
  'Pescatarian',
] as const;

export const COMMON_ALLERGIES = [
  'Peanuts',
  'Tree Nuts',
  'Shellfish',
  'Fish',
  'Eggs',
  'Milk',
  'Soy',
  'Wheat',
  'Sesame',
  'Gluten',
] as const;
